spring:
  application:
    name: twitter-analog

  data:
    mongodb:
      uri: mongodb://localhost:27017/twitter-analog
      database: twitter-analog

  security:
    user:
      name: user
      password: password

server:
  port: 8080

logging:
  level:
    root: INFO
    org.springframework: INFO
    com.example.twitterAnalog: DEBUG